name: "Tests"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 10 * * 1"

jobs:
  test84:
    name: "Tests on PHP 8.4"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: pdo, pdo_mysql
          coverage: none

      - run: composer update --no-interaction --no-progress

      - run: mysql -h 127.0.0.1 -u root mydb < tests/Fixtures/database.sql

      - run: make tests

  test83:
    name: "Tests on PHP 8.3"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pdo, pdo_mysql
          coverage: none

      - run: composer update --no-interaction --no-progress

      - run: mysql -h 127.0.0.1 -u root mydb < tests/Fixtures/database.sql

      - run: make tests

  test82:
    name: "Tests on PHP 8.2"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_mysql
          coverage: none

      - run: composer update --no-interaction --no-progress

      - run: mysql -h 127.0.0.1 -u root mydb < tests/Fixtures/database.sql

      - run: make tests

  lowest:
    name: "Tests on lowest dependencies"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_mysql
          coverage: none

      - run: composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest

      - run: mysql -h 127.0.0.1 -u root mydb < tests/Fixtures/database.sql

      - run: make tests
